# Generated by Django 5.1.3 on 2024-11-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
