# Generated by Django 5.1.3 on 2024-11-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productvariant_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbanail',
            new_name='thumbnail',
        ),
    ]
