# Generated by Django 5.1.3 on 2025-01-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
