# Generated by Django 5.1.3 on 2025-01-01 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
