# Generated by Django 5.1.3 on 2025-01-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_payment_status_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payment'), ('Wallet', 'Wallet Payment')], default='COD', max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
